name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      env:
        IMAGE_TAG: ${{ github.ref_name }}
      with:
        context: .
        push: true
        tags: |
          neoromantique/runpod-worker-a1111:${{ env.IMAGE_TAG//\//- }}
          neoromantique/runpod-worker-a1111:latest
